structure(list(method = "POST", url = "https://data.cityofchicago.org/d/zidz-sdfj", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 16:31:17 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Mon, 18 Aug 2025 05:24:06 GMT", 
        ETag = "W/\"DbtroKonLTaZz6ArLg4y8KNVSOUaH3Zw-QEBRXL_CQs\"", 
        `x-soda2-secondary` = "pg.pg14-c-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"district_name\",\"designation_date\"]", 
        `X-SODA2-Types` = "[\"text\",\"fixed_timestamp\"]", Age = "0", 
        `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "9d929f89dec617483068cdddaa724db6", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.3e-05, 
    connect = 0, pretransfer = 6.5e-05, starttransfer = 0.188264, 
    total = 0.188345), cache = new.env(parent = emptyenv())), class = "httr2_response")
