structure(list(method = "GET", url = "https://soda.demo.socrata.com/api/id/4tka-6guv?%24query=select%20count%28%2A%29%20as%20COLUMN_ALIAS_GUARD__count", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 17:23:07 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMzQxMl80XzEyMkNvS3hKT3ZjMW95TWZtSjlLeHdxTW13SjdJSQ-aClGsWGhfmTX8bRCcybPwEZxa7w--gzip--gzip\"", 
        `X-SODA2-Fields` = "[\"COLUMN_ALIAS_GUARD__count\"]", 
        `X-SODA2-Types` = "[\"number\"]", `X-SODA2-Data-Out-Of-Date` = "false", 
        `X-SODA2-Truth-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "6733f831b6abfa57ed0ef9653b85f648"), class = "httr2_headers"), 
    body = charToRaw("[{\"COLUMN_ALIAS_GUARD__count\":\"10821\"}]\n"), 
    timing = c(redirect = 0, namelookup = 2.9e-05, connect = 0, 
    pretransfer = 0.000111, starttransfer = 0.088062, total = 0.088148
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
