[format]
line-width = 80
indent-width = 2
indent-style = "space"
line-ending = "lf"
persistent-line-breaks = true
exclude = ["R/import-standalone-obj-type.R", "R/import-standalone-types-check.R"]
default-exclude = true