structure(list(method = "GET", url = "https://data.cityofchicago.org/api/id/zidz-sdfj?%24query=select%20count%28%2A%29%20as%20COLUMN_ALIAS_GUARD__count", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Fri, 11 Jul 2025 20:09:34 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC43Mzc2XzRfMjhUSXdZSGJaTzZSa2REOVoyeEZaSTAyWTh2RGc--gziOgMq5yUQ4_K54MXGqG8rmgwsPHs---gzip\"", 
        `X-SODA2-Fields` = "[\"COLUMN_ALIAS_GUARD__count\"]", 
        `X-SODA2-Types` = "[\"number\"]", `X-SODA2-Data-Out-Of-Date` = "false", 
        `X-SODA2-Truth-Last-Modified` = "Mon, 19 Aug 2019 01:27:09 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Mon, 19 Aug 2019 01:27:09 GMT", 
        `Last-Modified` = "Mon, 19 Aug 2019 01:27:09 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "cff348168a99885d5cb5d195cf3956c8"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("[{\"COLUMN_ALIAS_GUARD__count\":\"59\"}]\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
