structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/2646-ez2p.json?%24offset=0&%24limit=2", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Fri, 11 Jul 2025 20:09:37 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMDE0NF8yXzExTTcwNEg4NUZMWUM2NnBjQm5JQk9qSzZzX3VV---gzipHmtz5r73BM4hH7xxMpI91aCuqNE--gzip--gzip\"", 
        `X-SODA2-Fields` = "[\"domain\",\"name\",\"logo\",\"tags\",\"email\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"text\",\"text\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", 
        `Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "decd38d9a80ef4941d1ea9d95b1d48a8"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("[{\"domain\":\"data.seattle.gov\",\"name\":\"City of Seattle\",\"tags\":\"seattle, open data, washington, open government\",\"email\":\"open-data@seattle.gov\"}\n,{\"domain\":\"data.sfgov.org\",\"name\":\"City of San Francisco\",\"tags\":\"san francisco, california, open data\",\"email\":\"open-data@sfgov.org\"}]\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
