structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/2646-ez2p.json?%24limit=10000", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 20:42:13 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMDE0NF8yXzExM2x2YTdBak0yM0QxOTExdEg2MmYzbzFKWUFN---gzipJLo3Ni65qDfm912j4UsbJQ_vXoc--gzip--gzip\"", 
        `X-SODA2-Fields` = "[\"domain\",\"name\",\"logo\",\"tags\",\"email\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"text\",\"text\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", 
        `Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "e171094107ed0017ae43bb0af4f16f6a"), class = "httr2_headers"), 
    body = charToRaw("[{\"domain\":\"data.seattle.gov\",\"name\":\"City of Seattle\",\"tags\":\"seattle, open data, washington, open government\",\"email\":\"open-data@seattle.gov\"}\n,{\"domain\":\"data.sfgov.org\",\"name\":\"City of San Francisco\",\"tags\":\"san francisco, california, open data\",\"email\":\"open-data@sfgov.org\"}]\n"), 
    timing = c(redirect = 0, namelookup = 2.5e-05, connect = 0, 
    pretransfer = 7.8e-05, starttransfer = 0.207107, total = 0.207173
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
