structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/kc76-ybeq.json?%24offset=0&%24limit=5", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Fri, 11 Jul 2025 20:09:32 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zOTEyOF8yXzc2NTY1WVpvSWhZVFAwN01sNDZCNXBQMUM0Z3VEY0U--gzi5vPVmCJxh8b2FpDO7xbmUHf1abY---gzip\"", 
        `X-SODA2-Fields` = "[\"x\",\"y\"]", `X-SODA2-Types` = "[\"number\",\"number\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Fri, 24 May 2019 17:40:18 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Fri, 24 May 2019 17:40:18 GMT", 
        `Last-Modified` = "Fri, 24 May 2019 17:40:18 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "b034de77bb7497295468a1dbb231eca0"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("[{\"x\":\"112\",\"y\":\"663\"}\n,{\"x\":\"-798\",\"y\":\"-93\"}\n,{\"x\":\"317\",\"y\":\"-58\"}\n,{\"x\":\"-853\",\"y\":\"-797\"}\n,{\"x\":\"185\",\"y\":\"102\"}]\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
