structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/w8wm-g3qx.json?%24offset=0&%24limit=3", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Sat, 12 Jul 2025 07:04:51 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC41NjgxNV8yXzE1azFPeDZKVkJWUHdULXZ5VW16WUZqLVh3NU53--gzih6WOPa_GCc4l2x9pJQAs0KAf6WZ---gzip\"", 
        `X-SODA2-Fields` = "[\"text\",\"checkbox\"]", `X-SODA2-Types` = "[\"text\",\"boolean\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", 
        `Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "2d181f6dc5dd077e63dd1582ed2b9b78"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("[{\"text\":\"True\",\"checkbox\":true}\n,{\"text\":\"Null\"}\n,{\"text\":\"False\",\"checkbox\":false}]\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
