structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/w8wm-g3qx.json?%24limit=3", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 17:23:08 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC41NjgxNV8yXzE1eWpiUmtnbmVTYUFDYkFvaWZOaTBiUDV5Szdr--gzioTnanL2c351vucMthUOTxs7v_T2---gzip\"", 
        `X-SODA2-Fields` = "[\"text\",\"checkbox\"]", `X-SODA2-Types` = "[\"text\",\"boolean\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", 
        `Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "f64b8281ba5a2276ef9b1b5e719a90d1"), class = "httr2_headers"), 
    body = charToRaw("[{\"text\":\"True\",\"checkbox\":true}\n,{\"text\":\"Null\"}\n,{\"text\":\"False\",\"checkbox\":false}]\n"), 
    timing = c(redirect = 0, namelookup = 1.1e-05, connect = 0, 
    pretransfer = 5.2e-05, starttransfer = 0.10239, total = 0.102521
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
