structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/2asz-g9qq/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:12:42 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Mon, 18 Aug 2025 05:23:46 GMT", 
        ETag = "W/\"daN_SZSMSGiA2Xddcle9_APMi-Qwm4UaZTO0AT5BLaQ\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"plain_text_column\",\"html\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\"]", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "add8a15e8e4f7740a4d12fdbeaccd674", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.6e-05, 
    connect = 0, pretransfer = 8.3e-05, starttransfer = 0.299025, 
    total = 0.299095), cache = new.env(parent = emptyenv())), class = "httr2_response")
