structure(list(method = "POST", url = "https://soda.demo.socrata.com/d/4tka-6guv", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 16:31:05 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Mon, 18 Aug 2025 16:31:05 GMT", 
        ETag = "W/\"ztRKBuVhFRlG_qCa9_gcfo6BCvuanxpbiSkYWb-O_p8\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "false", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"magnitude\",\"count\"]", `X-SODA2-Types` = "[\"number\",\"number\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "1d4bc418af4e08f616d111a2ca810fbf", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.4e-05, 
    connect = 0, pretransfer = 7.4e-05, starttransfer = 0.293125, 
    total = 0.293215), cache = new.env(parent = emptyenv())), class = "httr2_response")
