structure(list(method = "POST", url = "https://soda.demo.socrata.com/d/4tka-6guv", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 16:31:03 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 15:06:22 GMT", 
        ETag = "W/\"TxHvcrpwaNjlJiHe2gEs0L_285fHtFMHKY3QUvd_9to\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"source\",\"earthquake_id\",\"version\",\"magnitude\",\"depth\",\"number_of_stations\",\"region\",\"location\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"number\",\"number\",\"number\",\"text\",\"location\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "c1e59181acdb7462717f495cc9a38544", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.4e-05, 
    connect = 0, pretransfer = 8.3e-05, starttransfer = 0.204475, 
    total = 0.204557), cache = new.env(parent = emptyenv())), class = "httr2_response")
