structure(list(method = "GET", url = "https://soda.demo.socrata.com/api/id/jatp-jqxg?%24query=select%20count%28%2A%29%20as%20COLUMN_ALIAS_GUARD__count", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 17:23:12 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMDE4MV8yXzIxQ0lGSi1PU2xMLTA1eFNoLW1ycXRGU1h6M2tN--gzijoDKuclEOPyueDFxqhvK5oMLDx7---gzip\"", 
        `X-SODA2-Fields` = "[\"COLUMN_ALIAS_GUARD__count\"]", 
        `X-SODA2-Types` = "[\"number\"]", `X-SODA2-Data-Out-Of-Date` = "false", 
        `X-SODA2-Truth-Last-Modified` = "Tue, 26 Apr 2016 23:01:08 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Tue, 26 Apr 2016 23:01:08 GMT", 
        `Last-Modified` = "Tue, 26 Apr 2016 23:01:08 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "818dd4b52bdd87d3ae758a47afa0a2ac"), class = "httr2_headers"), 
    body = charToRaw("[{\"COLUMN_ALIAS_GUARD__count\":\"10\"}]\n"), 
    timing = c(redirect = 0, namelookup = 2.4e-05, connect = 0, 
    pretransfer = 7.6e-05, starttransfer = 0.104009, total = 0.104074
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
