structure(list(method = "GET", url = "https://soda.demo.socrata.com/api/id/kc76-ybeq?%24query=select%20count%28%2A%29%20as%20COLUMN_ALIAS_GUARD__count", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 17:23:09 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zOTEyOF8yXzc2NTZQMFBvRGdQSkh1LVF4b3BJZk14UTJJYjUxWTA--gziOgMq5yUQ4_K54MXGqG8rmgwsPHs---gzip\"", 
        `X-SODA2-Fields` = "[\"COLUMN_ALIAS_GUARD__count\"]", 
        `X-SODA2-Types` = "[\"number\"]", `X-SODA2-Data-Out-Of-Date` = "false", 
        `X-SODA2-Truth-Last-Modified` = "Fri, 24 May 2019 17:40:18 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Fri, 24 May 2019 17:40:18 GMT", 
        `Last-Modified` = "Fri, 24 May 2019 17:40:18 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "27956ab43fbf812a756b58027ec35e7c"), class = "httr2_headers"), 
    body = charToRaw("[{\"COLUMN_ALIAS_GUARD__count\":\"5\"}]\n"), 
    timing = c(redirect = 0, namelookup = 1.5e-05, connect = 0, 
    pretransfer = 4.8e-05, starttransfer = 0.188552, total = 0.188701
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
