structure(list(method = "GET", url = "https://soda.demo.socrata.com/api/id/w8wm-g3qx?%24query=select%20count%28%2A%29%20as%20COLUMN_ALIAS_GUARD__count", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 17:23:08 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC41NjgxNV8yXzE1YV9UcmR6RG5SekdEQXBVSFBEcFVfd2hVc3U4--gzijoDKuclEOPyueDFxqhvK5oMLDx7---gzip\"", 
        `X-SODA2-Fields` = "[\"COLUMN_ALIAS_GUARD__count\"]", 
        `X-SODA2-Types` = "[\"number\"]", `X-SODA2-Data-Out-Of-Date` = "false", 
        `X-SODA2-Truth-Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", 
        `Last-Modified` = "Fri, 02 Dec 2016 17:45:50 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "5df798915a3960ae4636750c71fb5849"), class = "httr2_headers"), 
    body = charToRaw("[{\"COLUMN_ALIAS_GUARD__count\":\"3\"}]\n"), 
    timing = c(redirect = 0, namelookup = 1.6e-05, connect = 0, 
    pretransfer = 5.6e-05, starttransfer = 0.18567, total = 0.185838
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
