structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/4tka-6guv.json?%24select=magnitude%2C%20count%28%2A%29%20as%20count&%24where=magnitude%20%3E%206&%24group=magnitude&%24limit=10000", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 17:23:04 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMzQxMl80XzEyMmZteG1pelJmNzRrYVBFRHJjMGx3NTN4XzIxNA-aCMNYSK4O-mBYZH7LPgGE4wrqgY--gzip--gzip\"", 
        `X-SODA2-Fields` = "[\"magnitude\",\"count\"]", `X-SODA2-Types` = "[\"number\",\"number\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "a1ad9040d625a1edee44eda1f6820fb4"), class = "httr2_headers"), 
    body = charToRaw("[{\"magnitude\":\"6.1\",\"count\":\"6\"}\n,{\"magnitude\":\"6.2\",\"count\":\"4\"}\n,{\"magnitude\":\"6.4\",\"count\":\"1\"}\n,{\"magnitude\":\"6.5\",\"count\":\"2\"}\n,{\"magnitude\":\"6.6\",\"count\":\"4\"}]\n"), 
    timing = c(redirect = 0, namelookup = 2.1e-05, connect = 0, 
    pretransfer = 8.2e-05, starttransfer = 0.114998, total = 0.115089
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
