structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/4tka-6guv.json?%24select=source&%24limit=10", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Tue, 22 Jul 2025 20:42:08 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMzQxMl80XzEyMmVuZWgwWDZTaUdtQkxEdE1KNmNsbmxDYlpySQ-snCTtNYFd2g2moHeoksVS9IDWuM--gzip--gzip\"", 
        `X-SODA2-Fields` = "[\"source\"]", `X-SODA2-Types` = "[\"text\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "99bb2fc8170645a167ca0aa5f273ec56"), class = "httr2_headers"), 
    body = charToRaw("[{\"source\":\"hv\"}\n,{\"source\":\"ak\"}\n,{\"source\":\"ak\"}\n,{\"source\":\"ak\"}\n,{\"source\":\"uw\"}\n,{\"source\":\"us\"}\n,{\"source\":\"ak\"}\n,{\"source\":\"us\"}\n,{\"source\":\"ak\"}\n,{\"source\":\"us\"}]\n"), 
    timing = c(redirect = 0, namelookup = 1.1e-05, connect = 0, 
    pretransfer = 5.9e-05, starttransfer = 0.102198, total = 0.102229
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
