structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/2asz-g9qq/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:14:13 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Mon, 18 Aug 2025 06:14:13 GMT", 
        ETag = "W/\"gf6ast2KqykDj7gOVnFjmPLLrQG4juuKVEvYpoLBM3U\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "false", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"plain_text_column\",\"formatted_text_column\",\"number_column\",\"money_column\",\"percent_column\",\"date_time_column\",\"date_time_with_timezone_column\",\"location_column\",\"website_url_column\",\"email_column\",\"checkbox_column\",\"flag_column\",\"star_column\",\"phone_column\",\"multiple_choice\",\"photo_column\",\"document\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"number\",\"number\",\"number\",\"floating_timestamp\",\"fixed_timestamp\",\"location\",\"url\",\"text\",\"boolean\",\"text\",\"number\",\"text\",\"text\",\"photo\",\"document\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "b7756af40c049b71baf361f53d2683c9", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.6e-05, 
    connect = 0, pretransfer = 8.3e-05, starttransfer = 0.296442, 
    total = 0.296522), cache = new.env(parent = emptyenv())), class = "httr2_response")
