structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/2asz-g9qq/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:14:13 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Mon, 18 Aug 2025 06:14:13 GMT", 
        ETag = "W/\"qnCC1-Jbxsma0pHFbpdfmptlzvZ99P40vEaCU-fotMI\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "false", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"plain_text_column\",\"formatted_text_column\",\"number_column\",\"money_column\",\"percent_column\",\"date_time_column\",\"date_time_with_timezone_column\",\"location_column\",\"website_url_column\",\"email_column\",\"checkbox_column\",\"flag_column\",\"star_column\",\"phone_column\",\"multiple_choice\",\"photo_column\",\"document\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"number\",\"number\",\"number\",\"floating_timestamp\",\"fixed_timestamp\",\"location\",\"url\",\"text\",\"boolean\",\"text\",\"number\",\"text\",\"text\",\"photo\",\"document\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "5c8b5be60ec69dcd868a08e3881b3332", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n{\"plain_text_column\":\"Sample Text\",\"formatted_text_column\":\"<p>Sample <strong>Rich Text</strong></p>\",\"number_column\":\"42\",\"money_column\":\"1000000\",\"percent_column\":\"66\",\"date_time_column\":\"2014-10-13T00:00:00.000\",\"date_time_with_timezone_column\":\"2014-10-14T07:00:00.000Z\",\"location_column\":{\"latitude\":47.5982815480005,\"longitude\":-122.33477954499972,\"human_address\":\"{\\\"address\\\": \\\"83 South King Street\\\", \\\"city\\\": \\\"Seattle\\\", \\\"state\\\": \\\"WA\\\", \\\"zip\\\": \\\"\\\"}\"},\"website_url_column\":{\"url\":\"http://www.socrata.com\",\"description\":\"Socrata\"},\"email_column\":\"support@socrata.com\",\"checkbox_column\":true,\"flag_column\":\"green\",\"star_column\":\"3\",\"phone_column\":\"206-555-1212\",\"multiple_choice\":\"Maybe\",\"photo_column\":\"ZXF6YilAOjRH26G2TH05mvHMTlDnLCwn6CysLQP18hc\",\"document\":{\"file_id\":\"BFqKFH02U1wT_y_7EV_Llbka4p90HJrWkC-7ZalB2lA\",\"content_type\":\"image/gif; charset=binary\",\"filename\":\"ping-pong.gif\"}}\n]\n"), 
    timing = c(redirect = 0, namelookup = 1.4e-05, connect = 0, 
    pretransfer = 8e-05, starttransfer = 0.277271, total = 0.277402
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
