structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/4tka-6guv/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:12:55 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 15:40:57 GMT", 
        ETag = "W/\"OQ951h_jNw4e2CNP8fx5j4TvEYdfJB34zUEnXm6xqSk\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"source\"]", `X-SODA2-Types` = "[\"text\"]", 
        Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "6e645a101e8c461a081c324c150e726b", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.8e-05, 
    connect = 0, pretransfer = 8.3e-05, starttransfer = 0.190361, 
    total = 0.190441), cache = new.env(parent = emptyenv())), class = "httr2_response")
