structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/4tka-6guv/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:12:45 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 15:06:22 GMT", 
        ETag = "W/\"TxHvcrpwaNjlJiHe2gEs0L_285fHtFMHKY3QUvd_9to\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"source\",\"earthquake_id\",\"version\",\"magnitude\",\"depth\",\"number_of_stations\",\"region\",\"location\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"number\",\"number\",\"number\",\"text\",\"location\"]", 
        Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "62e0a87e5df829a2dbe36fcf3620ae82", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.5e-05, 
    connect = 0, pretransfer = 7.6e-05, starttransfer = 0.393765, 
    total = 0.393836), cache = new.env(parent = emptyenv())), class = "httr2_response")
