structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/4tka-6guv/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:12:54 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 15:40:57 GMT", 
        ETag = "W/\"Dd9cExqU-wwp6wALIq5GYBME_OhTJsd0CvJRzMYEsbc\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"source\"]", `X-SODA2-Types` = "[\"text\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "1b0b60dba79ec5f5d9f8ff442af47a15", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"},\n{\"source\":\"ak\"}\n]\n"), 
    timing = c(redirect = 0, namelookup = 1.2e-05, connect = 0, 
    pretransfer = 8.6e-05, starttransfer = 0.294196, total = 0.294295
    ), cache = new.env(parent = emptyenv())), class = "httr2_response")
