structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/2646-ez2p.json?%24limit=50000&%24offset=50000", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 26 May 2025 01:03:57 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMDE0NF8yXzExU1VzQk9qb1NLNXlQWnpvNW9lOGRMWWplUWRV--gziodgNW0xhEHwD-xA9TBoS1Ezlpoy---gzip\"", 
        `X-SODA2-Fields` = "[\"domain\",\"name\",\"logo\",\"tags\",\"email\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"text\",\"text\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", 
        `Last-Modified` = "Tue, 26 Apr 2016 23:01:00 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "fa95f400ad2036cb9f56228883c0445b"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("[]\n"), cache = new.env(parent = emptyenv())), class = "httr2_response")
