structure(list(method = "GET", url = "https://soda.demo.socrata.com/resource/6yvf-kk3n.json?%24limit=50000&%24offset=50000", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 26 May 2025 01:03:57 GMT", `Content-Type` = "application/json;charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", ETag = "\"Zm94dHJvdC4zMzQxMl80XzEyMl80ZThCMU94dDdSOTgxdFlaQUZVekowUGtsQQ---gzijbavdnCag195qMAkVRaVk0lkfHo--gzip--gzip\"", 
        `X-SODA2-Fields` = "[\"source\",\"earthquake_id\",\"version\",\"magnitude\",\"depth\",\"number_of_stations\",\"region\",\"location\",\"location_address\",\"location_city\",\"location_state\",\"location_zip\",\":@computed_region_k83t_ady5\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"number\",\"number\",\"number\",\"text\",\"point\",\"text\",\"text\",\"text\",\"text\",\"number\"]", 
        `X-SODA2-Data-Out-Of-Date` = "false", `X-SODA2-Truth-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `X-SODA2-Secondary-Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", 
        `Last-Modified` = "Wed, 04 Sep 2019 17:25:46 GMT", Vary = "Accept-Encoding", 
        `Content-Encoding` = "gzip", Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "949cb6b6c80ad4448e238843ec3d91da"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("[]\n"), cache = new.env(parent = emptyenv())), class = "httr2_response")
