# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib socratadata, .registration = TRUE
NULL

parse_data_resps <- function(resps, meta_url, tz) .Call(wrap__parse_data_resps, resps, meta_url, tz)

is_empty_raw_json <- function(raw_json) .Call(wrap__is_empty_raw_json, raw_json)

parse_discovery_resp <- function(resp) .Call(wrap__parse_discovery_resp, resp)

parse_metadata_resp <- function(resp) .Call(wrap__parse_metadata_resp, resp)

# nolint end
