# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_socratadata_wrappers", use_symbols = TRUE, package_name = "socratadata")

#' @usage NULL
#' @useDynLib socratadata, .registration = TRUE
NULL

parse_data_json <- function(raw_json, header_col_names, header_col_types, meta_url) .Call(wrap__parse_data_json, raw_json, header_col_names, header_col_types, meta_url)

is_empty_raw_json <- function(raw_json) .Call(wrap__is_empty_raw_json, raw_json)


# nolint end
