structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/7caz-dk9s/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:14:05 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 16:10:32 GMT", 
        ETag = "W/\"pXAsvdGvRAvRYLUOKCPE9YnGIpMhRJ1TLUiwUO_uRsA\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"url_with_description\",\"url_without_description\"]", 
        `X-SODA2-Types` = "[\"url\",\"url\"]", Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "d7737837440e5354c0f92c9c291cf17c", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.6e-05, 
    connect = 0, pretransfer = 7.8e-05, starttransfer = 0.295309, 
    total = 0.295363), cache = new.env(parent = emptyenv())), class = "httr2_response")
