structure(list(method = "POST", url = "https://soda.demo.socrata.com/d/2asz-g9qq", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 16:31:29 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 16:10:41 GMT", 
        ETag = "W/\"j3vDlPpa6REzQyiQwHn02efILpwgrAVoKB-gjkFffow\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"location_column\"]", `X-SODA2-Types` = "[\"location\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "8f059d56c8b48ed3f545a34803c66069", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.3e-05, 
    connect = 0, pretransfer = 6.7e-05, starttransfer = 0.154849, 
    total = 0.154934), cache = new.env(parent = emptyenv())), class = "httr2_response")
