structure(list(method = "POST", url = "https://soda.demo.socrata.com/d/jatp-jqxg", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 16:31:19 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Sun, 17 Aug 2025 16:10:27 GMT", 
        ETag = "W/\"RLLoiuEORaHxEVdt7Zq_MsekaO-EupsxNRyGJTNljmA\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"time\",\"updated\"]", `X-SODA2-Types` = "[\"floating_timestamp\",\"floating_timestamp\"]", 
        Age = "2", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "fcb7ecd9e23163804698899d537df681", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 1.5e-05, 
    connect = 0, pretransfer = 6.6e-05, starttransfer = 0.197592, 
    total = 0.197658), cache = new.env(parent = emptyenv())), class = "httr2_response")
