structure(list(method = "POST", url = "https://soda.demo.socrata.com/api/v3/views/2646-ez2p/query.json", 
    status_code = 200L, headers = structure(list(Server = "nginx", 
        Date = "Mon, 18 Aug 2025 06:14:02 GMT", `Content-Type` = "application/json; charset=utf-8", 
        `Transfer-Encoding` = "chunked", Connection = "keep-alive", 
        `Access-Control-Allow-Origin` = "*", `Last-Modified` = "Mon, 18 Aug 2025 05:24:12 GMT", 
        ETag = "W/\"w1aMayBsPFwQBrcwxBN6VBgKuXNFLYRrSjCAIHUPPKk\"", 
        `x-soda2-secondary` = "pg.pg15-a-fedramp-prod", `x-soda2-cached` = "true", 
        `x-soda2-data-out-of-date` = "[]", `X-SODA2-Warning` = "X-SODA2-Fields, X-SODA2-Types, and X-SODA2-Legacy-Types are deprecated", 
        `X-SODA2-Fields` = "[\"domain\",\"name\",\"logo\",\"tags\",\"email\"]", 
        `X-SODA2-Types` = "[\"text\",\"text\",\"text\",\"text\",\"text\"]", 
        Age = "0", `X-Socrata-Region` = "aws-us-east-1-fedramp-prod", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains", 
        `X-Socrata-RequestId` = "eb4da9559ce3b23294d3d3cb71b429ee", 
        `Content-Encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("[\n]\n"), timing = c(redirect = 0, namelookup = 2e-05, 
    connect = 0, pretransfer = 7.9e-05, starttransfer = 0.401511, 
    total = 0.401549), cache = new.env(parent = emptyenv())), class = "httr2_response")
